//TESTANDOO
GET  http://localhost:3003/ping

###
//ENDPOINT BUSCAR ESTUDANTES
GET  http://localhost:3003/estudante

###
//ENDPOINT BUSCAR TURMA
GET  http://localhost:3003/turma

###
//ENDPOINT BUSCAR DOCENTE
GET http://localhost:3003/docente